### ISSUE TITLE
submodule uses private url instead of public

### ISSUE THREAD

**Issue by morganrallen** [joshajohnson/Hub16#1]
should be https://github.com/joshajohnson/josh-kicad-lib.git

**Comment by joshajohnson** [comment]
Hi Morgan, I made that change however it then reverts back to HTTPS which is not desirable for my workflow. 

Are you cloning with SSH? Not sure of what errors you are seeing but [this](https://stackoverflow.com/questions/31184930/how-to-use-ssh-instead-of-http-for-git-submodules) may be a potential workaround. 

Let me know how you go, I'm not a git power user so have plenty to learn. 

Thanks!

**Comment by morganrallen** [comment]
Oh.. interestingly if I do checkout using SSH the submodule works fine. I was under the impression SSH access (including cloning) was only available to project maintainers. This introduces a bit of an odd quirk in git hosting but seems to work.

Excited for my Hub16 to arrive, got switches and keycaps yesterday so should be ready to roll.

**Comment by joshajohnson** [comment]
Glad to hear you got it sorted, I hadn't tried cloning it to a machine I don't have SSH on so was not sure what would happen. 

Woohoo, hopefully it arrives soon, any issues you where to let me know!
