### ISSUE TITLE
Is it possible to build this without the USB hub chip?

### ISSUE THREAD

**Issue by csn495** [joshajohnson/Hub16#13]
I was able to source all the parts needed except the USB hub chip (CY7C65632-28LTXCT).

If I were to build it this board without that chip would The device be able to communicate with the PC? Or does the main communication connection run through that chip as well?

I hope this question makes sense. Thanks in advance.

**Comment by joshajohnson** [comment]
Hi @csn495, you'd need to make a modification similar to [this](https://twitter.com/_joshajohnson/status/1289814962437632000/photo/1) for it to work without the USB hub IC. Otherwise you could respin the PCB to remove it and the excess USB ports. Thanks
