### ISSUE TITLE
Upgrading the firmware on old boards

### ISSUE THREAD

**Issue by charlesrocket** [joshajohnson/Hub16#5]
Is it safe to flash old boards with new firmware revisions? I can read the board with `qmk_toolbox` but wanted to confirm before bricking it :)

**Comment by joshajohnson** [comment]
Sure can, all boards (even V0.1 without a USB hub) run the same firmware / have the same pin connections. Revisions are design for manufacturing improvements as I went from assembling one for myself -> small production by hand -> mass production.
