### ISSUE TITLE
Link to build tools is broken

### ISSUE THREAD

**Issue by voltagex** [joshajohnson/Hub16#6]
https://docs.qmk.fm/#/getting_started_build_tools is 404, but QMK links to that too. I *guess* https://docs.qmk.fm/#/newbs_getting_started is an OK replacement.

**Comment by joshajohnson** [comment]
Thanks Adam, the build instructions have changed dramatically since I wrote the instructions, and was not aware of the change.
If there are any issues building with the new getting started guide let me know and I'll look into it.
