### ISSUE TITLE
Disabling the power LED

### ISSUE THREAD

**Issue by tmilloff** [joshajohnson/Hub16#8]
Is it possible to disable the power LED without desoldering it?

**Comment by joshajohnson** [comment]
If your board has a jumper labeled "LED" (some of the early versions did not), cut that with a knife and it will disable the LED.
Otherwise I'll get some CAD with where to cut.

I will update the documentation to make this more clear.

**Comment by tmilloff** [comment]
Just to clarify, will that only disable the power LED, not the RGB backlighting?

**Comment by joshajohnson** [comment]
Yes, correct. 
Sorry for the confusion on this, should have documented this much better.
